# open a file

[[session]]
name = "Home ğŸ¡"
path = "~"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/dotfiles/"
startup_command = "nvim .tmux.conf"

[[session]]
name = "sesh conf"
path = "~/dotfiles/sesh.toml"
startup_command = "nvim sesh.toml"


[[session]]
name = "yiali-sesh"
path = "~"
startup_command = "tmuxifier load-session yiali && tmux kill-session -t yiali-sesh"

